# Generated by Django 4.2.30 on 2026-06-26 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_providergallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_providers', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services_app.providerprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoriteprovider',
            constraint=models.UniqueConstraint(fields=('customer', 'provider'), name='unique_favorite_provider'),
        ),
    ]
